version: "3.8"
services:
  pbkk-pos-app:
    container_name: pbkk-pos-app
    image: bitnami/laravel
    volumes:
      - ./src:/var/www/html
    env_file: .env
    dns:
      - 1.1.1.1
      - 1.0.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true